version: "2"

run:
  timeout: 2m

linters:
  default: none
  enable:
    # 检查未处理的 error
    - errcheck
    # Go 官方静态检查，发现代码潜在错误
    - govet
    # 检查无效赋值（赋值后未使用）
    - ineffassign
    # 检查拼写错误，代码/注释都查
    - misspell
    # 功能强大的代码质量与错误检测，规则多，能查性能和安全问题
    - staticcheck

#    # 接下来是一些进阶版的规则,可有可无
#    # 检查函数/方法的圈复杂度，帮助代码简单化
#    - gocyclo
#    # - gofmt 检查代码是否未格式化,这个linter有bug,找了其他代替品,如果不需要我们就去除
#    # 检查 import 语句分组和排序
#    - goimports
#    # 官方代码风格建议，注重注释和命名规范
#    - golint
#    # 检查重复出现的字符串常量是否可提取为常量
#    - goconst
#    # 检查函数签名是否可用 interface 优化
#    - interfacer
#    # 检查 HTTP 响应体是否被关闭
#    - bodyclose

issues:
  exclude-use-default: false

