#!/usr/bin/env bash
set -e

# 创建脚本目录
mkdir -p scripts

# 检查是否在Android项目根目录
if [ ! -f "build.gradle" ] && [ ! -f "build.gradle.kts" ]; then
  echo "⚠️  当前目录不是Android项目根目录"
  echo "   请确保在包含 build.gradle 或 build.gradle.kts 的目录下运行此脚本"
  exit 1
fi

# 检测项目类型
PROJECT_TYPE="unknown"
if [ -f "settings.gradle.kts" ] || [ -f "build.gradle.kts" ]; then
  PROJECT_TYPE="kotlin-dsl"
elif [ -f "settings.gradle" ] || [ -f "build.gradle" ]; then
  PROJECT_TYPE="groovy-dsl"
fi

echo "🔍 检测到项目类型: $PROJECT_TYPE"

# 生成 lint.xml 配置文件
cat <<EOF > lint.xml
<?xml version="1.0" encoding="UTF-8"?>
<lint>
    <!-- 错误级别规则 -->
    <issue id="HardcodedText" severity="error" />
    <issue id="MissingTranslation" severity="error" />
    <issue id="UnusedResources" severity="error" />
    <issue id="IconMissingDensityFolder" severity="error" />
    <issue id="SecurityLogCatch" severity="error" />
    <issue id="LogConditional" severity="error" />
    
    <!-- 警告级别规则 -->
    <issue id="UselessParent" severity="warning" />
    <issue id="InefficientWeight" severity="warning" />
    <issue id="NestedWeights" severity="warning" />
    <issue id="DisableBaselineAlignment" severity="warning" />
    <issue id="ObsoleteLayoutParam" severity="warning" />
    <issue id="Overdraw" severity="warning" />
    
    <!-- 性能相关 -->
    <issue id="DrawAllocation" severity="warning" />
    <issue id="Recycle" severity="error" />
    <issue id="WakelockTimeout" severity="warning" />
    
    <!-- 安全相关 -->
    <issue id="AllowBackup" severity="warning" />
    <issue id="ExportedActivity" severity="warning" />
    <issue id="ExportedReceiver" severity="warning" />
    <issue id="ExportedService" severity="warning" />
    
    <!-- 忽略的规则 -->
    <issue id="GoogleAppIndexingWarning" severity="ignore" />
    <issue id="LintBaseline" severity="ignore" />
    
    <!-- Kotlin 相关 -->
    <issue id="UnsafeCall" severity="error" />
    <issue id="NullSafeMutableLiveData" severity="warning" />
</lint>
EOF

# 生成 ktlint 配置文件 (.editorconfig)
cat <<EOF > .editorconfig
root = true

[*]
charset = utf-8
end_of_line = lf
indent_style = space
indent_size = 4
insert_final_newline = true
max_line_length = 120
trim_trailing_whitespace = true

[*.{kt,kts}]
indent_size = 4
continuation_indent_size = 4

[*.{xml,html}]
indent_size = 4

[*.{json,yml,yaml}]
indent_size = 2

[*.md]
trim_trailing_whitespace = false
EOF

# 生成 .gitignore（如果不存在）
if [ ! -f ".gitignore" ]; then
cat <<EOF > .gitignore
# Built application files
*.apk
*.aab

# Files for the ART/Dalvik VM
*.dex

# Java class files
*.class

# Generated files
bin/
gen/
out/
release/

# Gradle files
.gradle/
build/

# Local configuration file (sdk path, etc)
local.properties

# Proguard folder generated by Eclipse
proguard/

# Log Files
*.log

# Android Studio Navigation editor temp files
.navigation/

# Android Studio captures folder
captures/

# IntelliJ
*.iml
.idea/workspace.xml
.idea/tasks.xml
.idea/gradle.xml
.idea/assetWizardSettings.xml
.idea/dictionaries
.idea/libraries
.idea/jarRepositories.xml
.idea/caches
.idea/modules.xml
.idea/.name
.idea/compiler.xml
.idea/copyright/profiles_settings.xml
.idea/encodings.xml
.idea/scopes/scope_settings.xml
.idea/vcs.xml
.idea/jsLibraryMappings.xml
.idea/datasources.xml
.idea/dataSources.ids
.idea/sqlDataSources.xml
.idea/dynamic.xml
.idea/uiDesigner.xml

# OS-specific files
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db

# Android Lint
lint-results.html
lint-results_files/
lint-report.txt

# Ktlint
.ktlint

# Backup files
*.bak
EOF
fi

# 根据项目类型生成 Gradle 配置
if [ "$PROJECT_TYPE" = "kotlin-dsl" ]; then
  # Kotlin DSL 项目配置
  cat <<'EOF' > gradle-config.kts
// 将以下内容添加到你的 app/build.gradle.kts 文件中

android {
    lint {
        // 启用 lint 检查
        abortOnError = true
        warningsAsErrors = false
        checkDependencies = true
        checkGeneratedSources = false
        explainIssues = true
        
        // 忽略的文件和目录
        ignoreTestSources = true
        ignoreTestFixturesSources = true
        
        // 输出格式
        htmlReport = true
        htmlOutput = file("$buildDir/reports/lint/lint-results.html")
        xmlReport = true
        xmlOutput = file("$buildDir/reports/lint/lint-results.xml")
        
        // 使用配置文件
        lintConfig = file("../lint.xml")
        
        // 基线文件
        baseline = file("lint-baseline.xml")
    }
    
    // Ktlint 配置
    // 在项目根目录的 build.gradle.kts 添加：
    /*
    plugins {
        id("org.jlleitschuh.gradle.ktlint") version "11.6.1" apply false
    }
    */
    
    // 在 app/build.gradle.kts 添加：
    /*
    plugins {
        id("org.jlleitschuh.gradle.ktlint")
    }
    
    ktlint {
        version.set("0.50.0")
        debug.set(false)
        verbose.set(true)
        android.set(true)
        outputToConsole.set(true)
        outputColorName.set("RED")
        ignoreFailures.set(false)
        enableExperimentalRules.set(false)
        
        filter {
            exclude("**/generated/**")
            include("**/kotlin/**")
        }
    }
    */
}
EOF
else
  # Groovy DSL 项目配置
  cat <<'EOF' > gradle-config.gradle
// 将以下内容添加到你的 app/build.gradle 文件中

android {
    lint {
        // 启用 lint 检查
        abortOnError true
        warningsAsErrors false
        checkDependencies true
        checkGeneratedSources false
        explainIssues true
        
        // 忽略的文件和目录
        ignoreTestSources true
        ignoreTestFixturesSources true
        
        // 输出格式
        htmlReport true
        htmlOutput file("$buildDir/reports/lint/lint-results.html")
        xmlReport true
        xmlOutput file("$buildDir/reports/lint/lint-results.xml")
        
        // 使用配置文件
        lintConfig file("../lint.xml")
        
        // 基线文件
        baseline file("lint-baseline.xml")
    }
}

// Ktlint 配置
// 在项目根目录的 build.gradle 添加：
/*
plugins {
    id "org.jlleitschuh.gradle.ktlint" version "11.6.1" apply false
}
*/

// 在 app/build.gradle 添加：
/*
apply plugin: "org.jlleitschuh.gradle.ktlint"

ktlint {
    version = "0.50.0"
    debug = false
    verbose = true
    android = true
    outputToConsole = true
    outputColorName = "RED"
    ignoreFailures = false
    enableExperimentalRules = false
    
    filter {
        exclude("**/generated/**")
        include("**/kotlin/**")
    }
}
*/
EOF
fi

# 生成 Makefile
cat <<EOF > Makefile
.PHONY: lint ktlint format commit commit-force
lint:
	./gradlew lint

ktlint:
	./gradlew ktlintCheck

format:
	./gradlew ktlintFormat

commit:
	bash scripts/android-smart-commit.sh

commit-force:
	bash scripts/android-smart-commit.sh --force

setup:
	@echo "📋 请手动完成以下配置："
	@echo "1. 将 gradle-config.${PROJECT_TYPE} 中的内容添加到对应的 Gradle 文件"
	@echo "2. 运行 ./gradlew ktlintApplyToIdea 来配置 Android Studio"
	@echo "3. 使用 'make lint' 运行 Android Lint 检查"
	@echo "4. 使用 'make ktlint' 运行 Ktlint 检查"
	@echo "5. 使用 'make format' 自动格式化 Kotlin 代码"
EOF

# 生成 Android 智能提交脚本
cat <<'EOF' > scripts/android-smart-commit.sh
#!/usr/bin/env bash
set -e

# 检查强制模式
FORCE_MODE=false
if [[ "$1" == "--force" ]]; then
  FORCE_MODE=true
fi

# 检查是否在Android项目根目录
if [ ! -f "build.gradle" ] && [ ! -f "build.gradle.kts" ]; then
  echo "❌ 错误：请在Android项目根目录下运行此脚本"
  exit 1
fi

# 自动添加文件变更
if [ -n "$(git diff --name-only)" ] || [ -n "$(git diff --cached --name-only)" ]; then
  echo "📦 检测到文件变更，自动执行 git add ."
  git add .
fi

echo ""
echo "✨ Step 1: Ktlint 格式化"
if [ -f "gradlew" ]; then
  # 询问是否需要格式化
  read -p "🤔 是否运行 Ktlint 自动格式化？(Y/n): " FORMAT_CONFIRM
  FORMAT_CONFIRM=${FORMAT_CONFIRM:-y}
  
  if [[ "$FORMAT_CONFIRM" =~ ^[Yy]$ ]]; then
    echo "🔧 正在运行 Ktlint 格式化..."
    if ./gradlew ktlintFormat > /dev/null 2>&1; then
      echo "✅ Ktlint 格式化完成"
      if [ -n "$(git diff --name-only)" ]; then
        echo "📦 格式化后检测到文件变更，自动暂存"
        git add .
      fi
    else
      echo "⚠️ Ktlint 格式化失败，可能项目未配置 Ktlint"
    fi
  else
    echo "⏩ 跳过 Ktlint 格式化"
  fi
else
  echo "⚠️ 未找到 gradlew，跳过 Ktlint 格式化"
fi

echo ""
echo "🔍 Step 2: 运行 Ktlint 检查..."
if [ -f "gradlew" ]; then
  if ./gradlew ktlintCheck; then
    echo "✅ Ktlint 检查通过"
  else
    echo "⛔ Ktlint 检查失败"
    if [ "$FORCE_MODE" = false ]; then
      read -p "🤔 是否继续提交？(y/N): " CONTINUE_CONFIRM
      CONTINUE_CONFIRM=${CONTINUE_CONFIRM:-n}
      if [[ ! "$CONTINUE_CONFIRM" =~ ^[Yy]$ ]]; then
        echo "❌ 已取消提交"
        exit 1
      fi
    else
      echo "⚠️ 强制模式：忽略 Ktlint 错误继续提交"
    fi
  fi
else
  echo "⚠️ 未找到 gradlew，跳过 Ktlint 检查"
fi

echo ""
echo "🔍 Step 3: 运行 Android Lint 检查..."
if [ -f "gradlew" ]; then
  if ./gradlew lint; then
    echo "✅ Android Lint 检查通过"
  else
    echo "⛔ Android Lint 检查失败"
    echo "📋 查看详细报告: build/reports/lint/lint-results.html"
    if [ "$FORCE_MODE" = false ]; then
      read -p "🤔 是否继续提交？(y/N): " CONTINUE_CONFIRM
      CONTINUE_CONFIRM=${CONTINUE_CONFIRM:-n}
      if [[ ! "$CONTINUE_CONFIRM" =~ ^[Yy]$ ]]; then
        echo "❌ 已取消提交"
        exit 1
      fi
    else
      echo "⚠️ 强制模式：忽略 Android Lint 错误继续提交"
    fi
  fi
else
  echo "⚠️ 未找到 gradlew，跳过 Android Lint 检查"
fi

echo ""
echo "🤖 Step 4: 生成提交信息并提交..."
echo "📝 正在调用 GPTCommit 生成提交信息..."
git commit --quiet --no-edit
echo ""
echo "🎉 提交完成！"
EOF

chmod +x scripts/android-smart-commit.sh

# 创建示例 Kotlin Activity（如果 app/src/main/java 目录存在）
if [ -d "app/src/main/java" ]; then
  # 查找包名
  PACKAGE_DIR=$(find app/src/main/java -type d -mindepth 1 | head -1)
  if [ -n "$PACKAGE_DIR" ]; then
    PACKAGE_NAME=$(echo "$PACKAGE_DIR" | sed 's|app/src/main/java/||' | tr '/' '.')
    
    cat <<EOF > "${PACKAGE_DIR}/ExampleActivity.kt"
package ${PACKAGE_NAME}

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity

/**
 * 示例 Activity - 展示代码规范
 */
class ExampleActivity : AppCompatActivity() {
    
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        
        // 示例：符合 Kotlin 代码规范
        val message = getString(R.string.app_name)
        setupViews(message)
    }
    
    private fun setupViews(title: String) {
        // 代码实现
        supportActionBar?.title = title
    }
    
    companion object {
        private const val TAG = "ExampleActivity"
    }
}
EOF
    echo "📝 已创建示例文件: ${PACKAGE_DIR}/ExampleActivity.kt"
  fi
fi

echo ""
echo "✅ Android Lint/Ktlint 脚本与配置初始化完成！"
echo "   - lint.xml (Android Lint 规则配置)"
echo "   - .editorconfig (Ktlint 代码风格配置)"
echo "   - .gitignore (如果不存在)"
echo "   - gradle-config.${PROJECT_TYPE} (Gradle 配置示例)"
echo "   - scripts/android-smart-commit.sh (智能提交脚本)"
echo "   - Makefile (快捷命令)"
if [ -d "app/src/main/java" ]; then
echo "   - ExampleActivity.kt (示例代码文件)"
fi
echo ""
echo "🎯 下一步配置："
echo "   1. 运行 'make setup' 查看配置说明"
echo "   2. 将 gradle-config 中的内容添加到对应的 Gradle 文件"
echo "   3. 运行 'make lint' 检查 Android Lint"
echo "   4. 运行 'make ktlint' 检查 Kotlin 代码风格"
echo "   5. 使用 'make commit' 进行智能提交"
echo ""
echo "📖 常用命令："
echo "   • make lint         - 运行 Android Lint 检查"
echo "   • make ktlint       - 运行 Ktlint 检查"
echo "   • make format       - 自动格式化 Kotlin 代码"
echo "   • make commit       - 智能提交（格式化需询问，检查错误时会询问）"
echo "   • make commit-force - 强制提交（忽略 lint 错误）"
echo "" 